language:
- generic
compiler:
- gcc
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
  - os: osx
  allow_failures:
  - os: osx
  fast_finish: true
before_script:
- if [ $TRAVIS_OS_NAME == "osx" ]; then brew update -y; else sudo apt-get update -y
  -qq; fi
- if [ $TRAVIS_OS_NAME == "osx" ]; then brew install -y caskroom/cask/brew-cask && brew cask install -y mactex && sudo tlmgr update --self --all; else sudo apt-get install -y -qq texlive-fonts-recommended texlive-lang-japanese texlive-latex-base texlive-latex-extra texlive-science texlive-plain-generic latexmk ghostscript; fi
script:
- latexmk
